// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package cqupt

import (
	"errors"
	"fmt"
	"maps"
)

const (
	// CquptClientOperatorTelecom is a CquptClientOperator of type telecom.
	CquptClientOperatorTelecom CquptClientOperator = "telecom"
	// CquptClientOperatorCmcc is a CquptClientOperator of type cmcc.
	CquptClientOperatorCmcc CquptClientOperator = "cmcc"
	// CquptClientOperatorUnicom is a CquptClientOperator of type unicom.
	CquptClientOperatorUnicom CquptClientOperator = "unicom"
)

var ErrInvalidCquptClientOperator = errors.New("not a valid CquptClientOperator")

// String implements the Stringer interface.
func (x CquptClientOperator) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x CquptClientOperator) IsValid() bool {
	_, err := ParseCquptClientOperator(string(x))
	return err == nil
}

var _CquptClientOperatorValue = map[string]CquptClientOperator{
	"telecom": CquptClientOperatorTelecom,
	"cmcc":    CquptClientOperatorCmcc,
	"unicom":  CquptClientOperatorUnicom,
}

// ParseCquptClientOperator attempts to convert a string to a CquptClientOperator.
func ParseCquptClientOperator(name string) (CquptClientOperator, error) {
	if x, ok := _CquptClientOperatorValue[name]; ok {
		return x, nil
	}
	return CquptClientOperator(""), fmt.Errorf("%s is %w", name, ErrInvalidCquptClientOperator)
}

// MarshalText implements the text marshaller method.
func (x CquptClientOperator) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *CquptClientOperator) UnmarshalText(text []byte) error {
	tmp, err := ParseCquptClientOperator(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *CquptClientOperator) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

func (x CquptClientOperator) AllValues() map[string]CquptClientOperator {
	return maps.Clone(_CquptClientOperatorValue)
}

var _CquptClientOperatorNames = map[CquptClientOperator]string{
	CquptClientOperatorTelecom: "CquptClientOperatorTelecom",
	CquptClientOperatorCmcc:    "CquptClientOperatorCmcc",
	CquptClientOperatorUnicom:  "CquptClientOperatorUnicom",
}

func (x CquptClientOperator) Name() string {
	return _CquptClientOperatorNames[x]
}
