// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package cqupt

import (
	"errors"
	"fmt"
	"maps"
)

const (
	// CquptClientTypePC is a CquptClientType of type PC.
	CquptClientTypePC CquptClientType = "PC"
	// CquptClientTypeMobile is a CquptClientType of type Mobile.
	CquptClientTypeMobile CquptClientType = "Mobile"
)

var ErrInvalidCquptClientType = errors.New("not a valid CquptClientType")

// String implements the Stringer interface.
func (x CquptClientType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x CquptClientType) IsValid() bool {
	_, err := ParseCquptClientType(string(x))
	return err == nil
}

var _CquptClientTypeValue = map[string]CquptClientType{
	"PC":     CquptClientTypePC,
	"Mobile": CquptClientTypeMobile,
}

// ParseCquptClientType attempts to convert a string to a CquptClientType.
func ParseCquptClientType(name string) (CquptClientType, error) {
	if x, ok := _CquptClientTypeValue[name]; ok {
		return x, nil
	}
	return CquptClientType(""), fmt.Errorf("%s is %w", name, ErrInvalidCquptClientType)
}

// MarshalText implements the text marshaller method.
func (x CquptClientType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *CquptClientType) UnmarshalText(text []byte) error {
	tmp, err := ParseCquptClientType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *CquptClientType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

func (x CquptClientType) AllValues() map[string]CquptClientType {
	return maps.Clone(_CquptClientTypeValue)
}

var _CquptClientTypeNames = map[CquptClientType]string{
	CquptClientTypePC:     "CquptClientTypePC",
	CquptClientTypeMobile: "CquptClientTypeMobile",
}

func (x CquptClientType) Name() string {
	return _CquptClientTypeNames[x]
}
