// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package cqupt

import (
	"errors"
	"fmt"
)

const (
	// CquptLoginStatusPortalUnreachable is a CquptLoginStatus of type PortalUnreachable.
	CquptLoginStatusPortalUnreachable CquptLoginStatus = "PortalUnreachable"
	// CquptLoginStatusGatewayUnreachable is a CquptLoginStatus of type GatewayUnreachable.
	CquptLoginStatusGatewayUnreachable CquptLoginStatus = "GatewayUnreachable"
	// CquptLoginStatusNotLogin is a CquptLoginStatus of type NotLogin.
	CquptLoginStatusNotLogin CquptLoginStatus = "NotLogin"
	// CquptLoginStatusLoginButNotAvailable is a CquptLoginStatus of type LoginButNotAvailable.
	CquptLoginStatusLoginButNotAvailable CquptLoginStatus = "LoginButNotAvailable"
	// CquptLoginStatusLogin is a CquptLoginStatus of type Login.
	CquptLoginStatusLogin CquptLoginStatus = "Login"
)

var ErrInvalidCquptLoginStatus = errors.New("not a valid CquptLoginStatus")

// String implements the Stringer interface.
func (x CquptLoginStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x CquptLoginStatus) IsValid() bool {
	_, err := ParseCquptLoginStatus(string(x))
	return err == nil
}

var _CquptLoginStatusValue = map[string]CquptLoginStatus{
	"PortalUnreachable":    CquptLoginStatusPortalUnreachable,
	"GatewayUnreachable":   CquptLoginStatusGatewayUnreachable,
	"NotLogin":             CquptLoginStatusNotLogin,
	"LoginButNotAvailable": CquptLoginStatusLoginButNotAvailable,
	"Login":                CquptLoginStatusLogin,
}

// ParseCquptLoginStatus attempts to convert a string to a CquptLoginStatus.
func ParseCquptLoginStatus(name string) (CquptLoginStatus, error) {
	if x, ok := _CquptLoginStatusValue[name]; ok {
		return x, nil
	}
	return CquptLoginStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidCquptLoginStatus)
}
