// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package registry

import (
	"errors"
	"fmt"
)

const (
	// ExtraArgTypeFlag is a ExtraArgType of type Flag.
	ExtraArgTypeFlag ExtraArgType = "Flag"
	// ExtraArgTypeValue is a ExtraArgType of type Value.
	ExtraArgTypeValue ExtraArgType = "Value"
	// ExtraArgTypeListValue is a ExtraArgType of type ListValue.
	ExtraArgTypeListValue ExtraArgType = "ListValue"
)

var ErrInvalidExtraArgType = errors.New("not a valid ExtraArgType")

// String implements the Stringer interface.
func (x ExtraArgType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ExtraArgType) IsValid() bool {
	_, err := ParseExtraArgType(string(x))
	return err == nil
}

var _ExtraArgTypeValue = map[string]ExtraArgType{
	"Flag":      ExtraArgTypeFlag,
	"Value":     ExtraArgTypeValue,
	"ListValue": ExtraArgTypeListValue,
}

// ParseExtraArgType attempts to convert a string to a ExtraArgType.
func ParseExtraArgType(name string) (ExtraArgType, error) {
	if x, ok := _ExtraArgTypeValue[name]; ok {
		return x, nil
	}
	return ExtraArgType(""), fmt.Errorf("%s is %w", name, ErrInvalidExtraArgType)
}

// MarshalText implements the text marshaller method.
func (x ExtraArgType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ExtraArgType) UnmarshalText(text []byte) error {
	tmp, err := ParseExtraArgType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ExtraArgType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
